
if(!window.Jacob)window.Jacob={};Jacob=window.Jacob;(function(){Jacob.Codec.Base64={}
Jacob.Codec.Base64._keyStr="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=",Jacob.Codec.Base64.encode=function Jacob__Codec__Base64__encode(input){var output=[];var i=0;var chr1,chr2,chr3,enc1,enc2,enc3,enc4;input=Jacob.Codec.Base64._utf8_encode(input);while(i<input.length){chr1=input.charCodeAt(i++);chr2=input.charCodeAt(i++);chr3=input.charCodeAt(i++);enc1=chr1>>2;enc2=((chr1&3)<<4)|(chr2>>4);enc3=((chr2&15)<<2)|(chr3>>6);enc4=chr3&63;if(isNaN(chr2)){enc3=enc4=64;}else if(isNaN(chr3)){enc4=64;}
output.push([this._keyStr.charAt(enc1),this._keyStr.charAt(enc2),this._keyStr.charAt(enc3),this._keyStr.charAt(enc4)].join(''));}
return output.join('');};Jacob.Codec.Base64.decode=function Jacob__Codec__Base64__decode(input,utf8){var output=[],chr1,chr2,chr3,enc1,enc2,enc3,enc4,i=0;input=input.replace(/[^A-Za-z0-9\+\/\=]/g,"");while(i<input.length){enc1=this._keyStr.indexOf(input.charAt(i++));enc2=this._keyStr.indexOf(input.charAt(i++));enc3=this._keyStr.indexOf(input.charAt(i++));enc4=this._keyStr.indexOf(input.charAt(i++));chr1=(enc1<<2)|(enc2>>4);chr2=((enc2&15)<<4)|(enc3>>2);chr3=((enc3&3)<<6)|enc4;output.push(String.fromCharCode(chr1));if(enc3!=64){output.push(String.fromCharCode(chr2));}
if(enc4!=64){output.push(String.fromCharCode(chr3));}}
output=output.join('');if(utf8){output=Jacob.Codec.Base64._utf8_decode(output);}
return output;};Jacob.Codec.Base64.decodeAsArray=function Jacob__Codec__Base64___decodeAsArray(input){var dec=this.decode(input),ar=[],i;for(i=0;i<dec.length;i++){ar[i]=dec.charCodeAt(i);}
return ar;};Jacob.Codec.Base64._utf8_encode=function Jacob__Codec__Base64___utf8_encode(string){string=string.replace(/\r\n/g,"\n");var utftext="";for(var n=0;n<string.length;n++){var c=string.charCodeAt(n);if(c<128){utftext+=String.fromCharCode(c);}
else if((c>127)&&(c<2048)){utftext+=String.fromCharCode((c>>6)|192);utftext+=String.fromCharCode((c&63)|128);}
else{utftext+=String.fromCharCode((c>>12)|224);utftext+=String.fromCharCode(((c>>6)&63)|128);utftext+=String.fromCharCode((c&63)|128);}}
return utftext;};Jacob.Codec.Base64._utf8_decode=function Jacob__Codec__Base64___utf8_decode(utftext){var string=[],i=0,c=0,c2=0,c3=0;while(i<utftext.length){c=utftext.charCodeAt(i);if(c<128){string.push(String.fromCharCode(c));i++;}
else if((c>191)&&(c<224)){c2=utftext.charCodeAt(i+1);string.push(String.fromCharCode(((c&31)<<6)|(c2&63)));i+=2;}
else{c2=utftext.charCodeAt(i+1);c3=utftext.charCodeAt(i+2);string.push(String.fromCharCode(((c&15)<<12)|((c2&63)<<6)|(c3&63)));i+=3;}}
return string.join('');};Jacob.Codec.Base64._destrip=function Jacob__Codec__Base64___destrip(stripped,wrap){var lines=[],lineno,i,destripped=[];if(wrap==null)wrap=76;stripped.replace(/ /g,"");lineno=stripped.length/wrap;for(i=0;i<lineno;i++)lines[i]=stripped.substr(i*wrap,wrap);if(lineno!=stripped.length/wrap)
lines[lines.length]=stripped.substr(lineno*wrap,stripped.length-(lineno*wrap));for(i=0;i<lines.length;i++)destripped.push(lines[i]);return destripped.join('\n');};})();